package com.models;

// default package
// Generated 7 ���. 2023 �., 18:44:14 by Hibernate Tools 5.2.13.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderdetails generated by hbm2java
 */
@Entity
@Table(name = "orderdetails", catalog = "secondlabproductstore")
public class Orderdetails implements java.io.Serializable {

	private Integer orderDetailId;
	private Orders orders;
	private Products products;
	private int quantity;
	private BigDecimal subtotal;

	public Orderdetails() {
	}

	public Orderdetails(int quantity, BigDecimal subtotal) {
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	public Orderdetails(Orders orders, Products products, int quantity, BigDecimal subtotal) {
		this.orders = orders;
		this.products = products;
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OrderDetailID", unique = true, nullable = false)
	public Integer getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(Integer orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderID")
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Subtotal", nullable = false, precision = 10)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

}
