package com.models;

// default package
// Generated 7 ���. 2023 �., 18:44:14 by Hibernate Tools 5.2.13.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "secondlabproductstore")
public class Products implements java.io.Serializable {

	private Integer productId;
	private Categories categories;
	private String productName;
	private BigDecimal price;
	private int stockQuantity;
	private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);

	public Products() {
	}

	public Products(String productName, BigDecimal price, int stockQuantity) {
		this.productName = productName;
		this.price = price;
		this.stockQuantity = stockQuantity;
	}

	public Products(Categories categories, String productName, BigDecimal price, int stockQuantity,
			Set<Orderdetails> orderdetailses) {
		this.categories = categories;
		this.productName = productName;
		this.price = price;
		this.stockQuantity = stockQuantity;
		this.orderdetailses = orderdetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProductID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryID")
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@Column(name = "ProductName", nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "Price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "StockQuantity", nullable = false)
	public int getStockQuantity() {
		return this.stockQuantity;
	}

	public void setStockQuantity(int stockQuantity) {
		this.stockQuantity = stockQuantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Orderdetails> getOrderdetailses() {
		return this.orderdetailses;
	}

	public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
		this.orderdetailses = orderdetailses;
	}

}
